# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-30 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pass_wd',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.ImageField(default='static/blog/images/01.jpg', upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='users',
            name='nick_name',
            field=models.CharField(default='路人', max_length=60, verbose_name='昵称'),
        ),
    ]
