# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-07 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
    ]
